khmappers-khmap-614984d7132b/khmap/Models/MapPermissionsViewModel.cs
using MongoDB.Bson;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace khmap.Models
{
    public class MapPermissionsViewModel
    {
        public Map Map { get; set; }
        public KeyValuePair<ApplicationUser, MapPermissionType> Owner { get; set; }
        public Dictionary<ApplicationUser, MapPermissionType> Users { get; set; }
        public Dictionary<Group, MapPermissionType> Groups { get; set; }
        public MapPermissionType AllUsers { get; set; }
    }

    public class AddUserToMapViewModel
    {
        [Required]
        [Display(Name = "Map ID")]
        public string MId { get; set; }

        [Display(Name = "User ID")]
        public string UId { get; set; }

        [Required]
        [EmailAddress]
        [Display(Name = "User Email")]
        public string Email { get; set; }

        [Required]
        [Display(Name = "Permission")]
        public MapPermissionType Permission { get; set; }
    }

    public class MapUserPermissionViewModel
    {
        [Required]
        [Display(Name = "Map ID")]
        public string MId { get; set; }

        [Display(Name = "User ID")]
        public string UId { get; set; }

        [Required]
        [EmailAddress]
        [Display(Name = "User Email")]
        public string Email { get; set; }

        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required]
        [Display(Name = "Permission")]
        public MapPermissionType Permission { get; set; }
        public string PermissionString { get; set; }
    }


    public class MapGroupPermissionViewModel
    {
        [Required]
        [Display(Name = "Map ID")]
        public string MId { get; set; }

        [Display(Name = "Group ID")]
        public string GId { get; set; }

        [Required]
        [EmailAddress]
        [Display(Name = "Owner Email")]
        public string Email { get; set; }

        [Required]
        [Display(Name = "Group Name")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Permission")]
        public MapPermissionType Permission { get; set; }

        public string PermissionString { get; set; }
    }

}

khmappers-khmap-614984d7132b/khmap/Controllers/MapPermissionController.cs
using MongoDB.Bson;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using khmap.DataBaseProviders;
using Microsoft.Owin.Security;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using khmap.Models;

namespace khmap.Controllers
{
    [Authorize]
    public class MapPermissionController : Controller
    {

        private MapDB _mapManager;
        private UserDB _userService;
        private GroupDB _groupManager;
        private ApplicationUserManager _userManager;

        public MapPermissionController()
        {
            this._mapManager = new MapDB(new Settings());
            this._userService = new UserDB(new Settings());
            this._groupManager = new GroupDB(new Settings());
            //_userManager = UserManager;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }


        // GET: MapPermission
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult AddUserToMap(string mapId)
        {
            AddUserToMapViewModel m = new AddUserToMapViewModel { MId = mapId };
            return View(m);
        }

        [HttpPost]
        public ActionResult AddUserToMap(AddUserToMapViewModel model)
        {
            model.UId = UserManager.FindByEmail(model.Email).Id;
            if (AddUserToMap(model.UId.ToString(), model.MId.ToString(), model.Permission))
            {
                return View();
            }
            return View();
        }

        public Dictionary<ApplicationUser, MapPermissionType> GetUsersPermissions(string mapId)
        {
            var map = _mapManager.GetMapById(new ObjectId(mapId));
            Dictionary<ApplicationUser, MapPermissionType> users = new Dictionary<ApplicationUser, MapPermissionType>();
            foreach (var item in map.Permissions.Users)
            {
                var user = UserManager.FindById(item.Key.ToString());
                users.Add(user, item.Value);
            }
            return users;
        }

        public Dictionary<Group, MapPermissionType> GetGroupsPermissions(string mapId)
        {
            var map = _mapManager.GetMapById(new ObjectId(mapId));
            Dictionary<Group, MapPermissionType> groups = new Dictionary<Group, MapPermissionType>();
            foreach (var item in map.Permissions.Groups)
            {
                var group = _groupManager.GetGroupById(item.Key);
                groups.Add(group, item.Value);
            }
            return groups;
        }

        public MapPermissionType GetGlobalPermission(string mapId)
        {
            var map = _mapManager.GetMapById(new ObjectId(mapId));
            return map.Permissions.AllUsers;
        }

        public MapPermissionType GetOwnerPermission(string mapId)
        {
            var map = _mapManager.GetMapById(new ObjectId(mapId));
            return map.Permissions.Owner.Value;
        }

        public bool IsMapOwner(string mapId, string userId)
        {
            var map = _mapManager.GetMapById(new ObjectId(mapId));
            return map.Permissions.Owner.Key.ToString().Equals(userId);
        }

        public bool IsOwner(string mapId)
        {
            var map = _mapManager.GetMapById(new ObjectId(mapId));
            return User.Identity.GetUserId().Equals(map.Permissions.Owner.Key.ToString());
        }


        public KeyValuePair<ApplicationUser, MapPermissionType> GetMapOwner(string mapId)
        {
            var map = _mapManager.GetMapById(new ObjectId(mapId));
            var res = new KeyValuePair<ApplicationUser, MapPermissionType>(UserManager.FindById(map.Permissions.Owner.Key.ToString()), map.Permissions.Owner.Value);
            return res;
        }

        public MapPermissionType GetUserPermissionToMapAsUser(string mId, string uId)
        {
            if (string.IsNullOrEmpty(mId) || string.IsNullOrEmpty(uId))
            {
                return MapPermissionType.NA;
            }

            var user = _userService.GetUserById(new ObjectId(uId));
            var map = _mapManager.GetMapById(new ObjectId(mId));
            if (user == null || map == null)
            {
                return MapPermissionType.NA;
            }

            if (map.Permissions.Owner.Key == new ObjectId(user.Id))
            {
                return map.Permissions.Owner.Value;
            }
            if (map.Permissions.Users.Keys.Contains(new ObjectId(user.Id)))
            {
                return map.Permissions.Users[new ObjectId(user.Id)];
            }
            return MapPermissionType.NA;
        }

        public MapPermissionType GetUserPermissionToMapByGroup(string mId, string uId)
        {
            GroupController gc = new GroupController();
            var user = _userService.GetUserById(new ObjectId(uId));
            var map = _mapManager.GetMapById(new ObjectId(mId));
            var groups = map.Permissions.Groups.Where(x => gc.IsGroupMember(x.Key.ToString(), uId));
            var pers = groups.Select(x => x.Value).Distinct();
            if (pers.Contains(MapPermissionType.RW))
            {
                return MapPermissionType.RW;
            }
            else if (pers.Contains(MapPermissionType.RO))
            {
                return MapPermissionType.RO;
            }
            return MapPermissionType.NA;
        }

        public bool AddUserToMap(string uId, string mapId, MapPermissionType per)
        {
            if (IsOwner(mapId) && _userService.IsUserlExist(new ObjectId(uId)))
            {
                var map = _mapManager.GetMapById(new ObjectId(mapId));
                if (map != null && map.Creator.ToString() != uId)
                {
                    map.Permissions.Users[new ObjectId(uId)] = per;
                    _mapManager.UpdateMap(map);
                    return true;
                }
            }
            return false;
        }

        public bool AddGroupToMap(string gId, string mapId, MapPermissionType per)
        {
            if (_mapManager.IsMapExist(new ObjectId(mapId)) && _groupManager.IsGroupExist(new ObjectId(gId)) && IsOwner(mapId))
            {
                var map = _mapManager.GetMapById(new ObjectId(mapId));
                map.Permissions.Groups[new ObjectId(gId)] = per;
                _mapManager.UpdateMap(map);
                return true;
            }
            return false;
        }


        [HttpPost]
        public ActionResult AddNewUserToMap(string MId, string Email, MapPermissionType Permission = MapPermissionType.NA)
        {
            var user = _userService.GetUserByEmail(Email);
            if (AddUserToMap(user.Id, MId, Permission))
            {
                //return Json(new { success = true });
                return MyPermissions(MId);
            }
            return MyPermissions(MId);
        }


        public bool UpdateUserMapPermission(string uId, string mapId, MapPermissionType per)
        {
            return AddUserToMap(uId, mapId, per);
        }

        public bool UpdateGroupMapPermission(string gId, string mapId, MapPermissionType per)
        {
            return AddGroupToMap(gId, mapId, per);
        }

        public bool RemoveUserFromMap(string uId, string mapId)
        {
            if (IsOwner(mapId) && _userService.IsUserlExist(new ObjectId(uId)))
            {
                var map = _mapManager.GetMapById(new ObjectId(mapId));
                var ans = map.Permissions.Users.Remove(new ObjectId(uId));
                _mapManager.UpdateMap(map);
                return ans;
            }
            return false;
        }

        public bool RemoveGroupFromMap(string gId, string mapId)
        {
            if (IsOwner(mapId) && _groupManager.IsGroupExist(new ObjectId(gId)))
            {
                var map = _mapManager.GetMapById(new ObjectId(mapId));
                var ans = map.Permissions.Groups.Remove(new ObjectId(gId));
                _mapManager.UpdateMap(map);
                return ans;
            }
            return false;
        }



        /*
        public bool IsOwner(string id)
        {
            var uId = User.Identity.get
            ObjectId oId = new ObjectId(id);
            return 
        }
        */

        public JsonResult GetMapUserPermissionList(string mapId, int? page, int? limit, string sortBy, string direction, string searchString = null)
        {
            List<MapUserPermissionViewModel> mupvm = new List<MapUserPermissionViewModel>();
            var users = _mapManager.GetMapById(new ObjectId(mapId)).Permissions.Users;

            // users
            foreach (var uId in users.Keys)
            {
                var u = _userService.GetUserById(uId);
                mupvm.Add(new MapUserPermissionViewModel { MId = mapId, UId = uId.ToString(), Email = u.Email, FirstName = u.FirstName, LastName = u.LastName, Permission = users[uId], PermissionString = users[uId].ToString() });
            }

            // groups
            //var groups = _mapManager.GetMapById(new ObjectId(mapId)).Permissions.Groups;

            //foreach (var gId in groups.Keys)
            //{
            //    var g = _groupManager.GetGroupById(gId);
            //    mupvm.Add(new MapUserPermissionViewModel { MId = mapId, UId = gId.ToString(), Email = _userService.GetUserById(g.Creator).Email, Name = g.Name, Permission = groups[gId], PermissionString = groups[gId].ToString(), Type = "G" });
            //}

            var total = mupvm.Count();
            var records = mupvm.AsQueryable();;
            if (!string.IsNullOrWhiteSpace(searchString))
            {

khmappers-khmap-614984d7132b/khmap/Views/MapPermission/AddUserToMap.cshtml
@model khmap.Models.AddUserToMapViewModel


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AddUserToMapViewModel</h4>
        <hr />

        @Html.HiddenFor(m => m.MId)
        @Html.HiddenFor(m => m.UId)

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.permission, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.RadioButtonFor(model => model.permission, khmap.Models.MapPermissionType.RW, false) 
                @Html.RadioButtonFor(model => model.permission, khmap.Models.MapPermissionType.RO, true)
                @Html.ValidationMessageFor(model => model.permission, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

khmappers-khmap-614984d7132b/khmap/Views/MapPermission/_MapGroupNOPermissionsView.cshtml
@model khmap.Models.MapMiniViewModel

@*<div class="container-fluid fill">
    <div class="row">
        <div class="col-md-12">
            <div class="span12 well">*@
<div class="well">
    <h5><strong><i class="fa fa-users"></i> Groups Permissions</strong></h5>
    <hr />
    <div class="row">
        <div class="col-md-7">
            <div class="input-group">
                <input type="text" id="searchGroup" class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                    <button type="button" id="btnSearchGroup" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>
                </span>
            </div>
        </div>
        @*<div class="col-md-5">
            <button type="button" id="btnAddGroup" class="btn btn-primary pull-right"><i class="fa fa-plus"></i> Add Group</button>
        </div>*@
    </div>
    <br />
    <div class="row">
        <div class="col-md-12">
            <table id="mapGroupGrid" class="table" data-source="@Url.Action("GetMapGroupPermissionList", "MapPermission", new { mapId = Model.Id })"></table>
        </div>
    </div>
</div>
@*</div>
            </div>
        </div>
    </div>*@


<!-- Modal -->
<div class="modal fade" id="groupPermissionModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Edit Group Permission</h4>
            </div>
            <div class="modal-body">
                <form class="form form-horizontal">
                    <input type="hidden" id="gmid" />
                    <input type="hidden" id="ggid" />
                    <div class="form-group">
                        <label for="gname" class="control-label col-xs-3">Name</label>
                        <input type="text" class="form-control col-xs-8" id="gname" placeholder="Name" disabled />
                    </div>
                    <div class="form-group">
                        <label for="gpermission" class="control-label col-xs-3">Permission</label>
                        <div>
                            <select class="form-control col-xs-8" id="gpermission">
                                <option value="0">Read & Write (RW)</option>
                                <option value="1">Read Only (RO)</option>
                            </select>
                        </div>
                    </div>

                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" id="btnSaveGroup" class="btn btn-primary">Save</button>
            </div>
        </div>
    </div>
</div>


<!-- Add user Modal -->
<div class="modal fade" id="AddGroupPermissionModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Add Group Permission</h4>
            </div>
            <div class="modal-body">
                <form class="form form-horizontal">
                    <input type="hidden" id="addGroupMid" />
                    <input type="hidden" id="addGroupGid" />
                    <div class="form-group">
                        <label for="addGroupName" class="control-label col-xs-3">Group Name</label>
                        <input type="text" class="form-control col-xs-8" id="addGroupName" placeholder="Group Name" data-provide="typeahead" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <label for="addUserPermission" class="control-label col-xs-3">Permission</label>
                        <div>
                            <select class="form-control col-xs-8" id="addGroupPermission">
                                <option value="0">Read & Write (RW)</option>
                                <option value="1">Read Only (RO)</option>
                            </select>
                        </div>
                    </div>

                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" id="btnSaveNewGroup" class="btn btn-primary">Save</button>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">
    var mapGroupgrid;
    function AddGroup() {
        var mapId = '@Model.Id';
        $("#addGroupMid").val(mapId);
        $("#addGroupGid").val("");
        $("#addGroupName").val("");
        $("#addGroupPermission").val(0);
        $("#AddGroupPermissionModal").modal("show");
    }
    function SaveNewGroup() {
        var newGroup = {
            MId: $("#addGroupMid").val(),
            GId: $("#addGroupGid").val(),
            Permission: $("#addGroupPermission").val()
        };
        console.log(newGroup);
        $.ajax({ url: '@Url.Action("AddMapGroupPermission", "MapPermission")', type: "POST", data: { groupId: newGroup.GId, mapId: newGroup.MId, permission: newGroup.Permission } })
            .done(function () {
                mapGroupgrid.reload();
                $("#AddGroupPermissionModal").modal("hide");
            })
            .fail(function () {
                alert("Unable to save.");
                $("#AddGroupPermissionModal").modal("hide");
            });
    }
    function EditGroup(e) {
        //console.log(e.data);
        $("#gmid").val(e.data.record.MId);
        $("#ggid").val(e.data.id);
        $("#gname").val(e.data.record.Name);
        $("#gpermission").val(e.data.record.Permission);
        $("#groupPermissionModal").modal("show");
    }
    function SaveGroup() {
        var group = {
            MId: $("#gmid").val(),
            GId: $("#ggid").val(),
            Permission: $("#gpermission").val()
        };
        console.log(group);
        $.ajax({ url: '@Url.Action("SaveMapGroupPermission", "MapPermission")', type: "POST", data: { groupId: group.GId, mapId: group.MId, permission: group.Permission } })
            .done(function () {
                mapGroupgrid.reload();
                $("#groupPermissionModal").modal("hide");
            })
            .fail(function () {
                alert("Unable to save.");
                $("#groupPermissionModal").modal("hide");
            });
    }
    function RemoveGroup(e) {
        $.ajax({ url: '@Url.Action("RemoveMapGroupPermission", "MapPermission")', type: "POST", data: { groupId: e.data.id, mapId: e.data.record.MId } })
            .done(function () {
                mapGroupgrid.reload();
            })
            .fail(function () {
                alert("Unable to remove.");
            });
    }
    function SearchGroup() {
        mapGroupgrid.reload({ searchString: $("#searchGroup").val() });
    }

    $(document).ready(function () {
        mapGroupgrid = $("#mapGroupGrid").grid({
            dataKey: "GId",
            uiLibrary: "bootstrap",
            //width: 200,
            fontSize: "12px",
            columns: [
                { field: "MId", hidden: true },
                { field: "GId", hidden: true },
                { field: "Name", title: "Group Name", sortable: true, width: 100 },
                { field: "Email", title: "Owner Email", sortable: true, width: 150 },
                { field: "Permission", title: "Permission", hidden: true },
                { title: "Permission", tmpl: "{PermissionString}", sortable: true }
                //{ title: "", field: "Edit", width: 30, align: "center", type: "icon", icon: "glyphicon-pencil", tooltip: "Edit", events: { "click": EditGroup } },
                //{ title: "", field: "Delete", width: 30, align: "center", type: "icon", icon: "glyphicon-remove", tooltip: "Delete", events: { "click": RemoveGroup } }
            ],
            pager: { enable: true, limit: 5, sizes: [5, 10, 25, 50] }
        });
        //grid.on("cellDataBound", function (e, $wrapper, id, index, record) {
        //    if ("Type" === index) {
        //        $wrapper.addClass(record.Type.indexOf("U") > -1 ? "userCss" : "groupCss");
        //    }
        //});
        $("#btnAddGroup").on("click", AddGroup);
        $("#btnSaveGroup").on("click", SaveGroup);
        $("#btnSaveNewGroup").on("click", SaveNewGroup);
        $("#btnSearchGroup").on("click", SearchGroup);
    });

    $(document).ready(function () {
        console.log('blalalala');
        $("#addGroupName").typeahead({
            minLength: 1,
            source: function (query, process) {
                var groups = [];
                map = {};

                // This is going to make an HTTP post request to the controller
                return $.post('@Url.Action("GetGroupsNamesList", "Group")', { query: query }, function (data) {

                    // Loop through and push to the array
                    $.each(data, function (i, group) {
                        //console.log("i: " + i);
                        map[group.Name] = group;
                        groups.push(group.Name);
                    });

                    // Process the details
                    process(groups);
                });
            },
            updater: function (item) {
                console.log('item: ' + item);
                var gId = map[item].GroupId;

                // Set the text to our selected id
                $("#addGroupGid").val(gId);
                return item;
            }
        });
    });


</script>


<style>
    .form-horizontal .control-label {
        text-align: left !important;
    }

    .userCss {
        background-color: lightblue;
    }

    .groupCss {
        background-color: lightseagreen;
    }
</style>