khmappers-khmap-614984d7132b/khmap/Models/DetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace khmap.Models
{
    public class DetailsViewModel
    {
        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [Display(Name = "City")]
        public string City { get; set; }

        [Required]
        [Display(Name = "Country")]
        public string Country { get; set; }

        [Required]
        [Display(Name = "Joined at")]
        public DateTime CreationTime { get; set; }

        [Required]
        [Display(Name = "Reputation")]
        public double Reputation { get; set; }
    }
}

khmappers-khmap-614984d7132b/khmap/Models/MapFolder.cs
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using khmap.Models;

namespace khmap.Models
{   
    public class MapFolder
    {
        [BsonId]
        public ObjectId Id { get; set; }
        public string Name { get; set; }
        public HashSet<ObjectId> idOfMapsInFolder { get; set; }
        public HashSet<ObjectId> idOfSubFolders { get; set; }
        public ObjectId Creator { get; set; }
        public DateTime CreationTime { get; set; }
        public string Description { get; set; }
        public BsonDocument Model { get; set; }
        public MapPermissions Permissions { get; set; }
        public HashSet<ObjectId> Followers { get; set; }
        [BsonIgnoreIfNull]
        public ObjectId ParentDierctory { get; set; }
        public ObjectId FirstFolderOfUser { get; set; } // if this field wont hold the default objectid it's the first folder of the user with this id  


    }
}

khmappers-khmap-614984d7132b/khmap/Controllers/MapFolderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MongoDB.Bson;
using Microsoft.AspNet.Identity;
using khmap.DataBaseProviders;
using khmap.Models;

namespace khmap.Controllers
{
    public class MapFolderController : Controller
    {
        private MapFolderDB _mapFolderDataManager;
        private ApplicationUserManager _userManager;
        private MapDB _mapDataManager;
        private GroupDB _groupManager;
        //public static MapFolder STATIC_FOLDER;
        //public static MapFolder STATIC_INNER_FOLDER;

        public static string OWNED_SUPIRIOR = SharedCodedData.OWNED_SUPIRIOR;
        public static string SHARED_SUPIRIOR = SharedCodedData.SHARED_SUPIRIOR;
        public static string NOT_SUPIRIOR_BUT_SHARED = SharedCodedData.NOT_SUPIRIOR_BUT_SHARED;
        public static string NOT_SUPIRIOR_BUT_OWNED = SharedCodedData.NOT_SUPIRIOR_BUT_OWNED;



        public MapFolderController()
        {
            this._mapFolderDataManager = new MapFolderDB(new Settings());
            this._groupManager = new GroupDB(new Settings());
            this._mapDataManager = new MapDB(new Settings());
        }

        // GET: MapFolder
        public ActionResult Index(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                var Folderid = new ObjectId(id);
                var Folder = _mapFolderDataManager.GetMapFolderById(Folderid);
                if (Folder != null)
                {
                    var userId = User.Identity.GetUserId();
                    bool isFollowing = Folder.Followers.Contains(new ObjectId(userId), new IDComparer());
                    ViewBag.isFollowing = isFollowing;
                    MapPermissionController mpc = new MapPermissionController();
                    // MapViewModel mvm = new MapViewModel { Id = map.Id, Name = map.Name, CreationTime = map.CreationTime, CreatorId = map.Creator, CreatorEmail = UserManager.GetEmail(map.Creator.ToString()), Description = map.Description, Model = map.Model, ModelArchive = map.MapsArchive };

                    if (Folder.Permissions.Owner.Key.ToString().Equals(userId))
                    {
                        return View();
                    }
                    else
                    {
                        return View();
                    }
                }
            }
            return RedirectToAction("Index", "Home");
        }

        /** public ActionResult createFolder(MapFolder parent)
         {
             var id = User.Identity.GetUserId();
             ObjectId UserId = new ObjectId(id);
             MapFolder toadd = new MapFolder();
             toadd.Creator = UserId;
         }**/


        public ActionResult MyFirstMapAndFolders()
        {
            try
            {
                var id = User.Identity.GetUserId();
                ObjectId UserId = new ObjectId(id);
                MapFolder superiorMapFolder = _mapFolderDataManager.GetSuperiorMapFolderOfUserOwned(UserId);
                if(superiorMapFolder == null)
                {
                  //  superiorMapFolder = createSuppFolderLocaly(OWNED_SUPIRIOR);
                    _mapFolderDataManager.AddFolder(superiorMapFolder);
                }
                var mapFolders = this._mapFolderDataManager.GetAllSubFolder(superiorMapFolder);
         
                //var mapFolders = this._mapFolderDataManager.GetFirstFoldersOfUser(UserId);
                var maps = this._mapFolderDataManager.GetAllMapsInFolder(superiorMapFolder);
                _mapDataManager = new MapDB(new Settings());
                ViewBag.maps = maps;
                ViewBag.currFolder = superiorMapFolder;
                return PartialView("_MyFoldersView", mapFolders);
            }
            catch (Exception e)
            {
                string exp = e.ToString();
                //return RedirectToAction("Index", "Home");
                _mapDataManager = new MapDB(new Settings());
                ViewBag.maps = _mapDataManager.GetAllMaps();
                return PartialView("_MyFoldersView", new List<MapFolder>());

            }
        }

        public ActionResult Details(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                MapFolderDB _mfManeger = new MapFolderDB(new Settings());
                UserDB _userManeger = new UserDB(new Settings());

                var mId = new ObjectId(id);
                var folder = _mfManeger.GetMapFolderById(mId);
                if (folder != null)
                {
                    var userId = User.Identity.GetUserId();
                    bool isFollowing = folder.Followers.Contains(new ObjectId(userId), new IDComparer());
                    ViewBag.isFollowing = isFollowing;
                    FolderPermissionController fpc = new FolderPermissionController();
                    MapViewModel mvm = new MapViewModel { Id = folder.Id, Name = folder.Name, CreationTime = folder.CreationTime, CreatorId = folder.Creator, CreatorEmail = "not supported yet"/*UserManager.GetEmail(map.Creator.ToString())*/, Description = folder.Description, Model = folder.Model, ModelArchive = null };
                    if (fpc.IsFolderOwner(id, User.Identity.GetUserId()))
                    {
                        return View(mvm);
                    }
                    else
                    {
                        return View(mvm);
                    }
                }
            }
            return RedirectToAction("Index", "Home");
        }


        public ActionResult MyFirstMapAndFoldersShared()
        {
            try
            {
                var id = User.Identity.GetUserId();
                ObjectId UserId = new ObjectId(id);
                MapFolder superiorMapFolder = _mapFolderDataManager.GetSuperiorMapFolderOfUserShared(UserId);
                if (superiorMapFolder == null)
                {
                 //   superiorMapFolder = createSuppFolderLocaly(SHARED_SUPIRIOR);
                    _mapFolderDataManager.AddFolder(superiorMapFolder);
                }
                var mapFolders = this._mapFolderDataManager.GetAllSubFolder(superiorMapFolder);

                //var mapFolders = this._mapFolderDataManager.GetFirstFoldersOfUser(UserId);
                var maps = this._mapFolderDataManager.GetAllMapsInFolder(superiorMapFolder);
                _mapDataManager = new MapDB(new Settings());
                ViewBag.maps = maps;
                ViewBag.currFolder = superiorMapFolder;
                return PartialView("_MyFoldersView", mapFolders);
            }
            catch (Exception e)
            {
                string exp = e.ToString();
                //return RedirectToAction("Index", "Home");
                _mapDataManager = new MapDB(new Settings());
                ViewBag.maps = _mapDataManager.GetAllMaps();
                return PartialView("_MyFoldersView", new List<MapFolder>());

            }
        }


        public ActionResult OpenFolder(string Id)
        {
            string userIdAsString = User.Identity.GetUserId();
            ObjectId userObjectID = new ObjectId(userIdAsString);
            ObjectId parentID = new ObjectId(Id);
            var parent = new MapFolderDB(new Settings()).GetMapFolderById(parentID);
            if(parent.Model["type"].Equals(SharedCodedData.OWNED_SUPIRIOR))
            {
                parent = _mapFolderDataManager.GetSuperiorMapFolderOfUserOwned(userObjectID);
                parentID = parent.Id;
            }
            if (parent.Model["type"].Equals(SharedCodedData.SHARED_SUPIRIOR))
            {
                parent = _mapFolderDataManager.GetSuperiorMapFolderOfUserShared(userObjectID);
                parentID = parent.Id;
            }
            ObjectId prevFolderID = parent.ParentDierctory;
            var allFoldersOfUser = _mapFolderDataManager.GetAllMapFoldersOfUser(userObjectID);
            var allFolderOwnedByUsr = new List<MapFolder>();
            foreach(var folder in allFoldersOfUser)
            {
                if (folder.Permissions.Owner.Key.ToString().Equals(userObjectID.ToString()) && !folder.Model["type"].Equals(SharedCodedData.SHARED_SUPIRIOR))
                {
                    allFolderOwnedByUsr.Add(folder);
                }
            }
            ViewBag.allFoldersOfUser = allFolderOwnedByUsr;
            var prevFolder = new MapFolderDB(new Settings()).GetMapFolderById(prevFolderID);
            var mapFolders = this._mapFolderDataManager.GetAllSubFolder(parent);
            var maps = this._mapFolderDataManager.GetAllMapsInFolder(parent);
            ViewBag.maps = maps;
            ViewBag.currFolder = parent;
            ViewBag.currFolderID = parent.Id;
            ViewBag.currFolderIDString = parent.Id.ToString();

            ViewBag.prevFolder = prevFolder;
            if (prevFolder == null)
            {
                ViewBag.prevFolderID = null;
            }
            else
            {
                ViewBag.prevFolderID = prevFolder.Id;
            }
            if (prevFolder != null)
            {
                List<MapFolder> prevFOlderInList = new List<MapFolder>() { prevFolder };
                mapFolders = prevFOlderInList.Union(mapFolders);
                List<MapFolder> viewList = mapFolders.ToList();
            }
            return PartialView("_MyFoldersView", mapFolders);

        }


        public ActionResult OpenFolderShared(string Id)
        {
            string userIdAsString = User.Identity.GetUserId();
            ObjectId userObjectID = new ObjectId(userIdAsString);
            ObjectId parentID = new ObjectId(Id);
            var parent = new MapFolderDB(new Settings()).GetMapFolderById(parentID);
            bool isCurrentFolderSupp = false;
            if (parent.Model["type"].Equals(SharedCodedData.SHARED_SUPIRIOR))
            {

khmappers-khmap-614984d7132b/khmap/Views/MapFolder/Delete.cshtml
@model khmap.Models.MapDeleteViewModel

@{
    ViewBag.Title = "Delete";
}


<div class="well">
    <h3><b>Delete @Html.DisplayFor(model => model.Name)</b></h3>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatorEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatorEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreationTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    <hr />
    <h4>Are you sure you want to delete this map?</h4>
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <label class="btn btn-danger"  onclick="deleteFolder()">Delete</label>
            @*<input type="submit" value="Delete" class="btn btn-danger" />*@
            @Html.ActionLink("Cancel", "Index", "Home", new { id = Model.Id.ToString() }, new { @class = "btn btn-default", title = "Cancel" })
        </div>
    }
</div>

<div class="form-group" style="display:none">
    <label for="folderID">folderID</label>
    <input class="form-control" placeholder="folderID"
           type="text" id="folderID" value="@ViewBag.folderID" />
</div>

<div class="form-group" style="display:none">
    <label for="prevFolderID">prevFolderID</label>
    <input class="form-control" placeholder="prevFolderID"
           type="text" id="prevFolderID" value="@ViewBag.prevFolderID" />
</div>


<script>
    function deleteFolder() {
        var folderID = $('#folderID').val();
        var prevFolderID = $('#prevFolderID').val();

        $.ajax({
            type: "POST",
            url: '@Url.Action("deleteFolder", "MapFolder")',

            data: { currFolder: folderID },
            success: function () {
                window.location.href = '/map/Home/Index/' + prevFolderID;
            },
            error: function () {
                alert("Delete Failed!");
            }
        });
    }

</script>

<style>
    .dl-horizontal dt {
        text-align: left;
        margin-bottom: 0.5em;
        width: auto;
        padding-right: 0.5em;
    }
</style>

khmappers-khmap-614984d7132b/khmap/Views/MapFolder/Edit.cshtml
@model khmap.Models.MapEditViewModel

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal well">
        <h3><b>Edit @Html.DisplayFor(model => model.Name)</b></h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id, new { Value = Model.Id })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, 3, 0, new Dictionary<string, object>() { { "class", "form-control" }, { "style", "width:100%;" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Path, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Path, 3, 0, new Dictionary<string, object>() { {"id", "addGroupName" }, { "class", "form-control" }, { "style", "width:100%;" }, { "data-provide", "typeahead" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>




        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
                @Html.ActionLink("Cancel", "Details", "MapFolder", new { id = Model.Id.ToString() }, new { @class = "btn btn-default", title = "Cancel" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>

    $(document).ready(function () {
        console.log('blalalala');
        $("#addGroupName").typeahead({
            minLength: 1,
            source: function (query, process) {
                var groups = [];
                map = {};

                // This is going to make an HTTP post request to the controller
                return $.post('@Url.Action("GetUserFolderNames", "MapFolder", new {folderId = Model.Id})', { query: query }, function (data) {

                    // Loop through and push to the array
                    $.each(data, function (i, group) {
                        //console.log("i: " + i);
                        map[group.Name] = group;
                        groups.push(group.Name);
                    });

                    // Process the details
                    process(groups);
                });
            },
            updater: function (item) {
                console.log('item: ' + item);
                var gId = map[item].GroupId;

                // Set the text to our selected id
                $("#addGroupGid").val(gId);
                return item;
            }
        });
    });

</script>

<style>
    .form-horizontal .control-label {
        text-align: left !important;
    }
</style>

khmappers-khmap-614984d7132b/khmap/Views/MapFolder/Index.cshtml
@using Microsoft.AspNet.Identity;

@{
    ViewBag.Title = "Home Page";
    var name = Html.Action("GetUserFirstNameById", "User", new { id = User.Identity.GetUserId() });
}


<div class="well">
    <h2> @name's Home Page</h2>
</div>

<div class="col-md-6">
    <div class="span12 well" style="height:320px;padding-top:5px;" role="tabpanel">
        <h4>@name's Maps and Folders</h4>
        <div class="pull-right">
            @Html.ActionLink(" New Map", "OpenFolder", "MapFolder", new { id = Model.Id }, new { @class = "btn btn-primary" })
        </div>
        <ul class="nav nav-tabs" id="MapTab">
            <li role="presentation" class="active"><a href="#MyMaps" aria-controls="MyMaps" role="tab" data-toggle="tab">My Folders</a></li>
            <li role="presentation"><a href="#SharedMaps" aria-controls="SharedMaps" role="tab" data-toggle="tab">Shared Maps</a></li>
        </ul>
        <div class="tab-content" style="max-height:220px;overflow-y:auto;">
            <div role="tabpanel" class="tab-pane active" id="MyFirstMapAndFolders">@{ Html.RenderAction("MyFirstMapAndFolders", "MapFolder"); }</div>
            <div role="tabpanel" class="tab-pane" id="SharedMaps">@{ Html.RenderAction("MySharedMaps", "Map"); }</div>
        </div>
    </div>
</div>

<div class="col-md-6">
    <div class="span12 well" style="height:320px;padding-top:5px;" role="tabpanel">
        <h4>Groups</h4>
        <div class="pull-right">
            @Html.ActionLink("New Group", "Create", "Group", null, new { @class = "btn btn-primary" })
        </div>
        <ul class="nav nav-tabs" id="GroupTab">
            <li role="presentation" class="active"><a href="#MyGroups" aria-controls="MyGroups" role="tab" data-toggle="tab">My Groups</a></li>
            <li role="presentation"><a href="#MemberGroups" aria-controls="MemberGroups" role="tab" data-toggle="tab">Member Groups</a></li>
        </ul>

        <div class="tab-content" style="max-height:220px;overflow-y:auto;">
            <div role="tabpanel" class="tab-pane active" id="MyGroups">@{ Html.RenderAction("MyGroups", "Group"); } </div>
            <div role="tabpanel" class="tab-pane" id="MemberGroups">@{ Html.RenderAction("MyMemberGroups", "Group"); } </div>
        </div>
    </div>
</div>

khmappers-khmap-614984d7132b/khmap/Views/MapFolder/OpenFolder.cshtml
@using Microsoft.AspNet.Identity;
@model IEnumerable<khmap.Models.MapFolder>
@using khmap.Models;
@Scripts.Render("~/bundles/jquery")
@if (Model.Count() == 0)
{
    <div class="alert alert-info">No folders to display</div>
}
else
{
    <table class="table table-condensed table-responsive table-hover">
        @foreach (var item in Model)
        {
            <tr>
                <td class="col-md-1">
                    @*<span class="glyphicon glyphicon-star"></span>*@
                    <div id="tomerDIV">
                        <a id="tomer">hi</a>
                        <i class="fa fa-folder" aria-hidden="true">@Ajax.ActionLink(item.Name, "OpenFolder", new { Id = item.Id }, new AjaxOptions { UpdateTargetId = "blablabla" });</i>          @*this is the folder "button"*@
                    </div>
                    @*Html.ActionLink(item.Name, "OpenFolder", "MapFolder", new { id = item.Id }, new { @class = "fa fa-folder", title = @item.Name })
                        @**@
                </td>
                <td class="col-md-9">
                    @* @Html.ActionLink(item.Name, "OpenFolder", "MapFolder", new { id = item.Id }, new { title = "Open " + item.Name })*@
                    @try
                    {
                    }
                    catch (Exception e)
                    {

                    }
                </td>

                <td class="col-md-2">
                    @Html.ActionLink(" ", "", "", new { id = item.Id }, new { @class = "btn btn-info btn-xs glyphicon glyphicon-edit", title = "Details" })
                    @*@Html.ActionLink(" ", "LaunchMap5", "Map", new { id = item.Id.ToString() }, new { @class = "btn btn-success btn-xs glyphicon glyphicon-ok", title = "Load" })*@
                    @if (item.Creator.ToString() == User.Identity.GetUserId())
                    {
                        @Html.ActionLink(" ", "", "", new { id = item.Id }, new { @class = "btn btn-danger btn-xs glyphicon glyphicon-trash", title = "Delete" })
                    }
                    @Html.ActionLink(" ", "", "", new { id = item.Id }, new { @class = "btn btn-danger btn-xs glyphicon glyphicon-trash", title = "Delete" })


                </td>
            </tr>
        }

        @foreach (var map in ViewBag.maps)
        {
            <tr>
                <td class="col-md-1">
                    @*<span class="glyphicon glyphicon-star"></span>*@
                    <i class="fa fa-sitemap"></i>
                </td>
                <td class="col-md-9">
                    @Html.ActionLink(((Map)map).Name, "LaunchMap5", "Map", new { id = map.Id }, new { title = "Load " + map.Name })
                </td>

                <td class="col-md-2">
                    @Html.ActionLink(" ", "Index", "Map", new { id = map.Id }, new { @class = "btn btn-info btn-xs glyphicon glyphicon-edit", title = "Details" })
                    @*@Html.ActionLink(" ", "LaunchMap5", "Map", new { id = item.Id.ToString() }, new { @class = "btn btn-success btn-xs glyphicon glyphicon-ok", title = "Load" })*@
                    @if (((Map)map).Creator.ToString() == User.Identity.GetUserId())
                    {
                        @Html.ActionLink(" ", "Delete", "Map", new { id = map.Id }, new { @class = "btn btn-danger btn-xs glyphicon glyphicon-trash", title = "Delete" })
                    }
                </td>
            </tr>

        }

    </table>
}

<script>
    function openFoler() {

    }

</script>


<style>
    .table td {
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
        word-wrap: break-word;
    }

    .table {
        table-layout: fixed;
    }

    table tr {
        width: auto !important;
    }
</style>

khmappers-khmap-614984d7132b/khmap/Views/MapFolder/_MySharedFoldersView.cshtml
@using Microsoft.AspNet.Identity;
@model IEnumerable<khmap.Models.MapFolder>
@using khmap.Models;
@Scripts.Render("~/bundles/jquery")
@*if (Model.Count() == 0)
    {
        <div class="alert alert-info">No folders to display</div>
    }
    else
    {*@
    <table class="table table-condensed table-responsive table-hover">
 
        @if (true)
        {
            int i = 0;
            foreach (var item in Model)
            {
                string id = item.Id.ToString();
                string s = "0" + i.ToString();
                string name;
                if (i == 0 && ViewBag.prevFolder != null)
                {
                    name = "..";
                }
                else
                {
                    name = item.Name;
                }
               
                <tr>
                    <td class="col-md-2">
                        @if (ViewBag.prevFolder != null && i > 0)
                        {
                        <i>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</i>
                        }
                        <label id="@s" style="display:none">@id</label>
                        <i id="@id" onmousedown="onClickFolderShared(document.getElementById('@s').innerText, event, @i)" class="fa fa-folder" aria-hidden="true"><button class="btn-link"> @name</button></i>          @*this is the folder "button"*@
                    </td>
                    <td class="col-md-2">
                     @*   @Html.ActionLink(" ", "Details", "MapFolder", new { id = item.Id }, new { @class = "btn btn-info btn-xs glyphicon glyphicon-edit", title = "Details" })*@
                    </td>
                </tr>
                i++;
            }

            foreach (var map in ViewBag.maps)
            {

                string id = map.Id.ToString();
                string s = "0" + i.ToString();

                <tr>
                    <td class="col-md-9">
                        <label id="@s" style="display:none">@id</label>
                        <i id="@id" onmousedown="onClickMapShared(document.getElementById('@s').innerText, event, @i)" class="fa fa-sitemap" aria-hidden="true"><button class="btn-link"> @map.Name</button></i> 
                   @*     @Html.ActionLink(((Map)map).Name, "LaunchMap5", "Map", new { id = map.Id, currentFolderID = "null" }, new { title = "Load " + map.Name })*@
                    </td>
                @*
                    <td class="col-md-2">
                        @Html.ActionLink(" ", "Index", "Map", new { id = map.Id }, new { @class = "btn btn-info btn-xs glyphicon glyphicon-edit", title = "Details" })
                    </td>
                    *@
                </tr>
                i++;
            }
        }

    </table>

<div id="menuShared">
    <span id="detailsMenuButtonShared" class="menuItem">Details</span>
</div>
@*}*@

<script>
    var currentIDShared;
    var isFolderShared;

    function onClickMapShared(id, event, num) {
        currentIDShared = id;
        isFolderShared = false;
      //  alert(id);
        var element = document.getElementById(id);
      //  alert(element.innerText);
        element.oncontextmenu = function () { return false; }
        //alert(element.innerText);
        switch (event.which) {
            case 1:
                window.location.href = '@Url.Action("LaunchMap5", "Map", new {id = "ID", currentFolderID = "null" })'.replace("ID", id);
                break;
            case 2:
                console.log('Middle Mouse button pressed.');
                break;
            case 3:
                //alert("1");
                $("#menuShared").css('left', element.offsetLeft + 43 + element.offsetWidth);
                $("#menuShared").css('top', element.offsetTop + element.offsetHeight + (num + 1) * 30);
                $("#menuShared").show();
                //alert("2");
                break;
            default:
                console.log('You have a strange Mouse!');
        }
    }

    function onClickFolderShared(id, event, num) {
        currentIDShared = id;
        isFolderShared = true;
        //alert(currentID);
        var element = document.getElementById(currentIDShared);
        //alert("1");
        //alert(element.innerText);

        element.oncontextmenu = function () { return false; }
        switch (event.which) {
            case 1:
                //alert("1");
                window.location.href = '@Url.Action("Index", "Home", new {id = "ID", ownedOrShared = "shared" })'.replace("ID", id);
                break;
            case 2:
                console.log('Middle Mouse button pressed.');
                break;
            case 3:
             //   $("#menuShared").css('left', element.offsetLeft + 43 + element.offsetWidth);
             //   $("#menuShared").css('top', element.offsetTop + element.offsetHeight + (num+1) * 30);
                $("#menuShared").show();
                break;
            default:
                console.log('You have a strange Mouse!');
        }
    }

    $(document.body).mousedown(function (mouseEvent) {
        if (mouseEvent.which === 3) {
            $("#menuShared").css({
                'top': mouseEvent.pageY - 250,
                'left': mouseEvent.pageX - 150
            });
        }
    });

    $(document).ready(function () {
        $(document).click(function (e) {
            if (e.button == 0) {
                $("#menuShared").hide();
            }
        })
    })

    $(document).ready(function () {
        $("#detailsMenuButtonShared").click(function () {
            if (isFolderShared) {
                window.location.href = '@Url.Action("Details", "MapFolder", new {id = "ID"})'.replace("ID", currentIDShared);
            }
            else {
                window.location.href = '@Url.Action("Index", "Map", new {id = "ID"})'.replace("ID", currentIDShared);
            }
        })
    })

</script>



<style>
    .table td {
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
        word-wrap: break-word;
    }

    .table {
        table-layout: fixed;
    }

    table tr {
        width: auto !important;
    }

    #menuShared
    {
        background-color:#CDCDCD;
        border:2px solid #6A6A6A;
        border-radius:5px;
        box-shadow:5px 5px 10px #474747;
        width:130px;
        padding-top:5px;
        padding-bottom:5px;
        display:none;
        position:absolute;
    }
    .menuItem
    {
        padding-left:5px;
        padding-right:5px;
        font-family:Arial,Arial, Helvetica, sans-serif;
        
    }
    .menuItem:hover
    {
        font-weight:bold
    }


</style>