khmappers-khmap-614984d7132b/khmap/Controllers/MapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using khmap.DataBaseProviders;
using Microsoft.Owin.Security;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using MongoDB.Bson;
using khmap.Models;
using Newtonsoft.Json;
using MongoDB.Bson.IO;
using Newtonsoft.Json.Linq;
using System.IO;
using System.Web;
using System.Net;

namespace khmap.Controllers
{
    [Authorize]
    public class MapController : Controller
    {
        private MapDB _mapManager;
        private GroupDB _groupManager;
        private ApplicationUserManager _userManager;
        private MapFolderDB _folderManeger;
        private static string _currentFolderID;

        public MapController()
        {
            this._mapManager = new MapDB(new Settings());
            this._groupManager = new GroupDB(new Settings());
            this._folderManeger = new MapFolderDB(new Settings());
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }


        // GET: Map
        public ActionResult Index(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                var mId = new ObjectId(id);
                var map = _mapManager.GetMapById(mId);
                if (map != null)
                {
                    var userId = User.Identity.GetUserId();
                    bool isFollowing = map.Followers.Contains(new ObjectId(userId), new IDComparer());
                    ViewBag.isFollowing = isFollowing;
                    MapPermissionController mpc = new MapPermissionController();
                    MapViewModel mvm = new MapViewModel { Id = map.Id, Name = map.Name, CreationTime = map.CreationTime, CreatorId = map.Creator, CreatorEmail = UserManager.GetEmail(map.Creator.ToString()), Description = map.Description, Model = map.Model, ModelArchive = map.MapsArchive };
                    if (mpc.IsMapOwner(id, User.Identity.GetUserId()))
                    {
                        return View(mvm);
                    }
                    else
                    {
                        return View(mvm);
                    }
                }
            }
            return RedirectToAction("Index", "Home");
        }

        // GET: Map/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateMap(SaveMapViewModel newMapModel)
        {
            if (ModelState.IsValid)
            {
                var id = User.Identity.GetUserId();
                ObjectId oId = new ObjectId(id);

                MapPermissions mapPermissions = new MapPermissions();
                mapPermissions.Owner = new KeyValuePair<ObjectId, MapPermissionType>(oId, MapPermissionType.RW);
                mapPermissions.Users = new Dictionary<ObjectId, MapPermissionType>();
                mapPermissions.Groups = new Dictionary<ObjectId, MapPermissionType>();
                mapPermissions.AllUsers = MapPermissionType.NA;

                mapPermissions.Users.Add(oId, MapPermissionType.RW);

                BsonDocument bMapModel = BsonDocument.Parse(newMapModel.Model);
                //BsonDocument bMapModel = mapModel.ToBsonDocument();
                

                Queue<MapVersion> versions = new Queue<MapVersion>(MapVersion.VERSIONS);
                versions.Enqueue(new MapVersion { CreationTime = DateTime.Now, Model = bMapModel });

                Map map = new Map { Name = newMapModel.Name, Creator = oId, CreationTime = DateTime.Now, Description = newMapModel.Description, Model = bMapModel, Permissions = mapPermissions, MapsArchive = versions, Followers = new HashSet<ObjectId>() };
                var mId = _mapManager.AddMap(map);

                ObjectId mapID = new ObjectId(mId);
                string currentFolderIdString = _currentFolderID;
                ObjectId folderID = new ObjectId(currentFolderIdString);
                MapFolder folder = _folderManeger.GetMapFolderById(folderID);

                string path = folder.Model["path"].ToString();
                if (path.Equals(""))
                {
                    path = folder.Name;
                }
                else
                {
                    path = path + "/" + folder.Name;
                }
                bMapModel.Add("path", path);
                map.Model = bMapModel;
                _mapManager.UpdateMap(map);


                folder.idOfMapsInFolder.Add(mapID);
                _folderManeger.UpdateMapFolder(folder);

                return Json(new { mapId = mId, mapName = map.Name }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = false });
        }

        //[HttpPost]
        //public ActionResult CreateMap(string mapModel, string mapName, string mapDescription)
        //{
        //    //return Content("lalala");

        //    var id = User.Identity.GetUserId();
        //    ObjectId oId = new ObjectId(id);

        //    MapPermissions mapPermissions = new MapPermissions();
        //    mapPermissions.Owner = new KeyValuePair<ObjectId, MapPermissionType>(oId, MapPermissionType.RW);
        //    mapPermissions.Users = new Dictionary<ObjectId, MapPermissionType>();
        //    mapPermissions.Groups = new Dictionary<ObjectId, MapPermissionType>();
        //    mapPermissions.AllUsers = MapPermissionType.NA;

        //    mapPermissions.Users.Add(oId, MapPermissionType.RW);

        //    BsonDocument bMapModel = BsonDocument.Parse(mapModel);
        //    //BsonDocument bMapModel = mapModel.ToBsonDocument();

        //    Queue<MapVersion> versions = new Queue<MapVersion>(MapVersion.VERSIONS);
        //    versions.Enqueue(new MapVersion { CreationTime = DateTime.Now, Model = bMapModel });

        //    Map map = new Map { Name = mapName, Creator = oId, CreationTime = DateTime.Now, Description = mapDescription, Model = bMapModel, Permissions = mapPermissions, MapsArchive = versions, Followers = new HashSet<ObjectId>() };
        //    var mId = _mapManager.AddMap(map);


        //    return Json(mId, JsonRequestBehavior.AllowGet);
        //}

        [HttpPost]
        public ActionResult UpdateMap(string mapId, string mapModel)
        {
            if (!string.IsNullOrEmpty(mapId) && !string.IsNullOrEmpty(mapModel))
            {
                try
                {
                    var map = _mapManager.GetMapById(new ObjectId(mapId));
                    map.Model = BsonDocument.Parse(mapModel);
                    _mapManager.UpdateMap(map);
                    return Json(new { Success = true }, JsonRequestBehavior.AllowGet);
                }
                catch (Exception)
                {
                    return Json(new { Success = false }, JsonRequestBehavior.AllowGet);
                }
                
            }
            return Json(new { Success = false }, JsonRequestBehavior.AllowGet);
        }

        // GET: Map/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Map/Create
        [HttpPost]
        public ActionResult Create(MapCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var id = User.Identity.GetUserId();
                ObjectId oId = new ObjectId(id);

                MapPermissions mapPermissions = new MapPermissions();
                mapPermissions.Owner = new KeyValuePair<ObjectId,MapPermissionType>(oId, MapPermissionType.RW);
                mapPermissions.Users = new Dictionary<ObjectId,MapPermissionType>();
                mapPermissions.Groups = new Dictionary<ObjectId,MapPermissionType>();
                mapPermissions.AllUsers = MapPermissionType.NA;

                BsonDocument mapModel = new BsonDocument();

                Queue<MapVersion> versions = new Queue<MapVersion>(MapVersion.VERSIONS);
                versions.Enqueue(new MapVersion { CreationTime = DateTime.Now, Model = mapModel });

                Map map = new Map { Name = model.Name, Creator = oId, CreationTime = DateTime.Now, Description = model.Description, Model = mapModel, Permissions = mapPermissions, MapsArchive = versions };
                _mapManager.AddMap(map);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View();
            }
        }

        // GET: Map/Edit/5
        public ActionResult Edit(string id)
        {
            if (!IsValidId(id))
            {
                return RedirectToAction("Index", "Home");
            }
            try
            {
                var map = _mapManager.GetMapById(new ObjectId(id));
                if (IsValidMap(map) && _mapManager.IsMapOwner(map.Id.ToString(), User.Identity.GetUserId()))
                {
                    var mevm = new MapEditViewModel { Id = map.Id.ToString(), Name = map.Name, Description = map.Description };
                    return View(mevm);
                }
            }
            catch (Exception e)
            {
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Index", "Home");
        }

        // POST: Map/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MapEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var map = _mapManager.GetMapById(new ObjectId(model.Id));
                    map.Name = model.Name;
                    map.Description = model.Description;

khmappers-khmap-614984d7132b/khmap/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using khmap.DataBaseProviders;
using Microsoft.Owin.Security;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using MongoDB.Bson;
using khmap.Models;
using khmap.SearchDirectory;

namespace khmap.Controllers
{
    [Authorize]
    public class SearchController : Controller
    {

        private MapDB _mapManager;
        private UserDB _userService;
        private GroupDB _groupManager;
        private ApplicationUserManager _userManager;
        private ISearch _searchObj;

        public SearchController()
        {
            this._mapManager = new MapDB(new Settings());
            this._userService = new UserDB(new Settings());
            this._groupManager = new GroupDB(new Settings());
            _searchObj = new Search();
            //UserManager = UserManager;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: Search
        public ActionResult Index(string text)
        {
            SearchViewModel svm = new SearchViewModel();

            ObjectId userId = new ObjectId(User.Identity.GetUserId());
            //-------the way it was------
            //svm.Maps = _mapManager.SearchMap(text);
            //svm.Groups = _groupManager.SearchGroup(text);
            //svm.Users = _userService.SearchUser(text);
            //-------searhching combined------
            //Dictionary<ISearchType, Object> results = _searchObj.searchFunc(text, new List<ISearchType> { new SearchGroups(), new SearchMaps(), new SearchUsers() });
            //svm.Maps = _searchObj.getMapsOfResult(results);
            //svm.Groups = _searchObj.getGroupsOfResult(results);
            //svm.Users = _searchObj.getUsersOfResult(results);

            svm.Maps = _searchObj.searchMaps(text, userId);
            svm.Groups = _searchObj.searchGroups(text, userId);
            svm.Users = _searchObj.searchUsers(text, userId);
            svm.SearchText = text;
            return View(svm);
        }
    }
}

khmappers-khmap-614984d7132b/khmap/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Knowledge Map Project</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <link href="~/Content/themes/base/all.css" rel="stylesheet" type="text/css">
    <script src="~/Scripts/jquery-ui-1.11.4.min.js" type="text/javascript"></script>
    <link href="~/Content/grid-0.4.5.min.css" rel="stylesheet" type="text/css">
    <script src="~/Scripts/grid-0.4.5.js" type="text/javascript"></script>
    <script src="~/Scripts/bootstrap3-typeahead.min.js" type="text/javascript"></script>
    @*<link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">*@
    <link href="~/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    @*@Styles.Render("~/Content/jq-comment-css")
    @Scripts.Render("~/bundles/jq-comment-js")*@


</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Knowledge Map", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", null, new { @class = "active" })</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @*<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Create<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Create Map", "LaunchMap5", "Map")</li>
                            <li>@Html.ActionLink("Create Group", "Create", "Group")</li>
                        </ul>
                    </li>*@
                </ul>


            @using (Html.BeginForm("index", "Search"))
            {
                <div class="col-sm-3 col-md-3 toAlign">
                <form class="navbar-form" role="search">
                    <div class="input-group">
                        @*<input type="text" class="form-control" placeholder="Search" name="q">*@
                        @Html.TextBox("text", null, new { @class = "form-control", @placeholder = "Search" })
                        @*<input type="text" class="form-control" placeholder="Search" name="srch-term" id="srch-term">*@
                            <div class="input-group-btn">
                                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                            </div>
                        </div>
                    </form>
                </div>
            }
                
                @Html.Partial("_LoginPartial")

            </div>
        </div>
    </nav>


    <div class="container-fluid body-content toppad">
        @*<div class="container-fluid margin-top">*@
            <div class="row" @*style="margin-top: 15px;"*@>

                <div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 col-xs-offset-0 col-sm-offset-0 col-md-offset-2 col-lg-offset-1 toppad">

                    @*<div class="prettyprint linenums" id="content">*@
                    @RenderBody()

                    <hr />
                    <div class="col-md-12">
                    <footer>
                        @*<p>&copy; @DateTime.Now.Year - Knowledge Map Project, BGU</p>*@
                        <div>
                            <small class="pull-left">Copyright &copy; @DateTime.Now.Year <u><strong>Knowledge Map</strong></u>. All rights reserved.</small>
                        </div>
                    </footer>
                    </div>
                </div>

            </div>
            @*</div>*@
        @*</div>*@
        @*<hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Knowledge Map Project, BGU</p>
        </footer>*@
    </div>

        @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")*@
        @RenderSection("scripts", required: false)

    @*<link href="~/Content/themes/base/all.css" rel="stylesheet" type="text/css">
    <script src="~/Scripts/jquery-ui-1.11.4.min.js" type="text/javascript"></script>
    <link href="~/Content/grid-0.4.5.min.css" rel="stylesheet" type="text/css">
    <script src="~/Scripts/grid-0.4.5.js" type="text/javascript"></script>
    <script src="~/Scripts/bootstrap3-typeahead.min.js" type="text/javascript"></script>*@

    </body>
    </html>


<style type="text/css">
    .toppad {
        margin-top: 20px;
    }
    /* Fix alignment issue of label on extra small devices in Bootstrap 3.2 */
    .toAlign {
        padding-top: 7px;
    }
    
    body {
        background: #e9eaed;
    }

    .well {
        background-color: #FFFFFF;
        border: 1px solid;
        border-color: #e5e6e9 #dfe0e4 #d0d1d5;
        border-radius: 3px;
        /*border-width: 0.1em;*/
        box-sizing: border-box;
        /*box-shadow: inherit;*/
    }

    .form-horizontal .control-label {
        text-align: left !important;
    }

</style>